server:
  port: 8080
logging:
  level:
    org:
      springframework:
        jdbc:
          datasource:
            init:
              ScriptUtils: "debug"
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: "jdbc:h2:mem:testdb"
  jpa:
    hibernate:
      ddl-auto: "none"
database:
  host: localhost
  port: 3306
  name: securitydb
  user: root
  password: 1234
