server:
  port: 8080
logging:
  level:
    org:
      springframework:
        jdbc:
          datasource:
            init:
              ScriptUtils: "debug"
spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/securitydb?useSSL=false&serverTimezone=UTC
    username: root
    password: 1234
